// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CalmGlass.tsx": () => import("../components/mockups/CalmGlass.tsx"),
  "./components/mockups/NeonPulse.tsx": () => import("../components/mockups/NeonPulse.tsx"),
  "./components/mockups/OrbitDark.tsx": () => import("../components/mockups/OrbitDark.tsx")
};
